const colors = {
  lightGreen: '#0FB269',
  darkGreen: '#0C792B',
  greyInputPlaceholder: '#787878',
  greyInputBorder: '#dcdcdc',
  greyActiveInputBorder: '#8C8C8C',
  errorInputBorder: '#E86A5D',
  black: '#000',
  white: '#fff',
  defaultText: '#212145',
  lightGreyText: '#A5A5A5',
  emptyCheckBoxBorder: '#979797',
  amountInputButtonWrapperBg: '#E1E1E1',
  withdrawalNoteTextColor: '#222',
  transparent: 'transparent',
  selectedAccountBg: '#F5F5F5',
  accountDivider: '#F2F0FD',
  typeLabelDark: '#3A3A3A',
  typeLabelGreen: '#40B0AB',
  iosNativeModalBg: '#d2d5da',
  iosNativeModalHeaderBg: '#f5f5f5',
  iosNativeBlue: '#4f92fd',
  modalTopControl: '#C4C4C4',
  profileBodyBg: '#FBFBFB',
  chartGreen: '#70E5B1',
  chartLightGreen: '#74FFC1',
  profileEmail: '#268683',
  profileButtonBottomLayer: '#069C59',
  profileButtonText: '#85F0D6',
  profileBodyBorder: '#E0E0E0',
  profileIconColor: '#757575',
  transferFundsColor: '#16C5EA',
  darkHeader: '#171f22',
  profileHeaderBg: '#1C1C1D',
  navigationIconInactive: '#2D2D2D',
  activeFavoriteIcon: '#f7931a',
  blue: '#0366FF',
  transferDepositMoney: '#C7C7C7',
};

const fonts = {
  primary: {
    light: undefined,
    regular: undefined,
    bold: undefined,
  },
};

export { colors, fonts };
